jobs:
  stale:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/stale@v9
      with:
        close-issue-label: closed-as-inactive
        close-issue-message: Closing due to lack of requested feedback. If you would
          like us to look at this issue, please provide the requested information
          and we will re-open.
        close-pr-message: Closing due to lack of requested feedback. If you would
          like us to look at this, please provide the requested information and we
          will re-open.
        days-before-close: 7
        days-before-stale: 7
        exempt-all-milestones: true
        exempt-issue-labels: feedback-provided
        exempt-pr-labels: feedback-provided
        only-labels: waiting for feedback
        operations-per-run: 300
        stale-issue-label: feedback-reminder
        stale-issue-message: If you would like us to look at this issue, please provide
          the requested information. If the information is not provided within the
          next 7 days this issue will be closed.
        stale-pr-label: feedback-reminder
        stale-pr-message: If you would like us to look at this PR, please provide
          the requested information. If the information is not provided within the
          next 7 days this PR will be closed.
name: Close stale issues and PRs
on:
  repository_dispatch:
    types: trigger-ga___close-stale-issues.yml
